# Generated by Django 4.2.9 on 2025-05-17 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_id",
                    models.IntegerField(
                        help_text="기존 JSON에서 사용하던 ID", unique=True
                    ),
                ),
                ("name", models.CharField(help_text="학교 이름", max_length=100)),
            ],
            options={
                "verbose_name": "학교",
                "verbose_name_plural": "학교 목록",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SchoolDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text="학교 이메일 도메인 (예: example.ac.kr)",
                        max_length=100,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="utils.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "학교 도메인",
                "verbose_name_plural": "학교 도메인 목록",
                "unique_together": {("school", "domain")},
            },
        ),
    ]
