# Generated by Django 4.2.9 on 2025-02-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communityapp", "0003_postimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="type",
            field=models.CharField(
                choices=[
                    ("0", "랜덤채팅"),
                    ("1", "썸/연애"),
                    ("2", "주식/투자"),
                    ("3", "재수/반수/편입"),
                    ("4", "취업/창업"),
                    ("5", "여행/먹방"),
                    ("6", "게임"),
                    ("7", "패션/뷰티"),
                    ("8", "유머"),
                    ("9", "군대"),
                    ("10", "팀원모집/프로젝트"),
                    ("11", "만화/애니/영화"),
                    ("12", "일상"),
                    ("13", "연예인"),
                    ("14", "인생 꿀팁"),
                    ("15", "관리자공지"),
                    ("16", "관리자광고"),
                ],
                default="0",
                max_length=2,
            ),
        ),
    ]
